#undef UNICODE

[
	uuid (a791829b-a91a-43cf-bfd7-feeebe5150ad),
	version(1.0)
]

interface hello
{
	void HelloProc([in, string] unsigned char * pszString);
	void Shutdown(void);

	int Login([in, string] unsigned char * userName);
	void Logout(int id);
	int GetUsersList([out] char usersList[100][50]);
	int SendMyMessage(int id, [in, string] unsigned char * message, [in, string] unsigned char * receiver);

	int GetMessageStatus(int id, int messageId);
	int ReceiveMyMessage([out] char usersList[100], [out] char sender[100]);

}
