#undef UNICODE

#include <stdlib.h>
#include <stdio.h>
#include <ctype.h>
#include <locale.h>
#include "../com/chat_rpc.h" // header file generated by the MIDL compiler

void Usage(char *pszProgramName)
{
    //fprintf(stderr, "%s", PURPOSE);
    fprintf(stderr, "Usage:  %s\n", pszProgramName);
    fprintf(stderr, " -p protocol_sequence\n");
    fprintf(stderr, " -e endpoint\n");
    fprintf(stderr, " -m maxcalls\n");
    fprintf(stderr, " -n mincalls\n");
    fprintf(stderr, " -f flag_wait_op\n");

    exit(1);
}

void main(int argc, char *argv[])
{
    RPC_STATUS status;
    unsigned char *pszProtocolSequence = "ncacn_ip_tcp";
    unsigned char *pszSecurity = NULL;
    unsigned char *pszEndpoint = "33333";
    unsigned int cMinCalls = 1;
    unsigned int cMaxCalls = 20;
    unsigned int fDontWait = FALSE;
    int i;

    /* Allow the user to override settings with command line switches */

    for (i = 1; i < argc; i++)
    {
        if ((*argv[i] == '-') || (*argv[i] == '/'))
        {
            switch (tolower(*(argv[i] + 1)))
            {
            case 'p': // protocol sequence
                pszProtocolSequence = argv[++i];
                break;
            case 'e': // endpoint
                pszEndpoint = argv[++i];
                break;
            case 'm': // max concurrent calls
                cMaxCalls = (unsigned int)atoi(argv[++i]);
                break;
            case 'n': // min concurrent calls
                cMinCalls = (unsigned int)atoi(argv[++i]);
                break;
            case 'f': // flag
                fDontWait = (unsigned int)atoi(argv[++i]);
                break;
            case 'h':
            case '?':
            default:
                Usage(argv[0]);
            }
        }
        else
            Usage(argv[0]);
    }

    status = RpcServerUseProtseqEp(
        pszProtocolSequence,
        cMaxCalls,
        pszEndpoint,
        pszSecurity); // Security descriptor

    printf("RpcServerUseProtseqEp returned 0x%x\n", status);
    if (status)
        exit(status);

    status = RpcServerRegisterIf(
        //hello_ServerIfHandle,
        chat_v1_0_s_ifspec,
        NULL,  // MgrTypeUuid
        NULL); // MgrEpv; null means use default
    printf("RpcServerRegisterIf returned 0x%x\n", status);
    if (status)
        exit(status);

    status = RpcServerRegisterAuthInfo(

        NULL, // principal name

        RPC_C_AUTHN_WINNT, // auth server

        NULL, NULL);

    printf("RpcBindingSetAuthInfo returned 0x%x\n", status);

    if (status)
        exit(status);

    printf("Calling RpcServerListen\n");
    status = RpcServerListen(
        cMinCalls,
        cMaxCalls,
        fDontWait);
    printf("RpcServerListen returned: 0x%x\n", status);
    if (status)
        exit(status);

    if (fDontWait)
    {
        printf("Calling RpcMgmtWaitServerListen\n");
        status = RpcMgmtWaitServerListen(); // wait operation
        printf("RpcMgmtWaitServerListen returned: 0x%x\n", status);
        if (status)
            exit(status);
    }
}

/* MIDL allocate and free */
void __RPC_FAR *__RPC_API midl_user_allocate(size_t len)
{
    return (malloc(len));
}

void __RPC_API midl_user_free(void __RPC_FAR *ptr)
{
    free(ptr);
}
