#undef UNICODE
[
	uuid (a791829b-a91a-43cf-bfd7-feeebe5150ad),
	version(1.0)
]

interface chat
{
	const unsigned short USERS_COUNT = 100;
	const unsigned short MESSAGES_COUNT = 100;
	const unsigned short STR_LEN = 50;

	int Login([in, string] unsigned char * userName);
	void Logout([in] int userId);
	int GetUsersList([out] char usersList[USERS_COUNT][STR_LEN]);
	int SendMyMessage([in] int userId, [in, string] unsigned char * message, [in, string] unsigned char * receiver);

	int GetMessageStatus([in] int userId, [in] int messageId);
	int ReceiveMyMessage([in] int userId, [out] char sender[STR_LEN], [out] char message[STR_LEN]);
}
